FROM balenalib/raspberry-pi-debian:bullseye

WORKDIR /app

RUN apt-get update && apt-get install python3-pip python3-sense-hat

RUN pip install ptvsd==4.1.3
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

# Run script.
CMD [ "python3", "-u", "./main.py" ]